all:
		gcc -Wall -g --std=c99 -Werror statements.c -o statements
		gcc -Wall -g --std=c99 -Werror -pthread banks.c -o banks
		gcc -Wall -g --std=c99 -Werror stat.c -o stat
		gcc -Wall -g --std=c99 -Werror -D_DEFAULT_SOURCE list_dirs.c -o list_dirs
		gcc -Wall -g --std=c99 -Werror -D_DEFAULT_SOURCE list_dirs_recursively.c -o list_dirs_recursively
		gcc -Wall -g --std=c99 -Werror -D_DEFAULT_SOURCE list_dirs_rec.c -o listdirrec
